name: Release Version

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run publish-to-github
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
